In [3]:
import pandas as pd
from sklearn.metrics import mean_squared_error, r2_score
scores = "team_boxscore_stats_1997-19.csv"

In [110]:
scores_df = pd.read_csv(scores)
scores_df['WL'] = scores_df['WL'].map({'W': 1, 'L': 0})
scores_df.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS
0,21997,1610612763,VAN,Vancouver Grizzlies,29700014,10/31/1997,VAN vs. DAL,0.0,240,36,...,24,20,44,25,7,4,16,27,88,-2
1,21997,1610612742,DAL,Dallas Mavericks,29700014,10/31/1997,DAL @ VAN,1.0,240,32,...,10,27,37,18,5,8,18,21,90,2
2,21997,1610612741,CHI,Chicago Bulls,29700001,10/31/1997,CHI @ BOS,0.0,240,33,...,16,25,41,16,12,6,21,22,85,-7
3,21997,1610612738,BOS,Boston Celtics,29700001,10/31/1997,BOS vs. CHI,1.0,240,38,...,22,30,52,18,10,5,24,30,92,7
4,21997,1610612766,CHH,Charlotte Hornets,29700006,10/31/1997,CHH vs. NYK,0.0,240,26,...,13,29,42,16,4,2,18,32,85,-12

In [126]:
df_2017 =scores_df[47218:49677]
df_2017.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS
47218,22017,1610612738,BOS,Boston Celtics,21700001,10/17/2017,BOS @ CLE,0.0,240,36,...,9,37,46,24,11,4,12,24,99,-3
47219,22017,1610612739,CLE,Cleveland Cavaliers,21700001,10/17/2017,CLE vs. BOS,1.0,240,38,...,9,41,50,19,3,4,17,25,102,3
47220,22017,1610612744,GSW,Golden State Warriors,21700002,10/17/2017,GSW vs. HOU,0.0,240,43,...,6,35,41,34,5,9,17,25,121,-1
47221,22017,1610612745,HOU,Houston Rockets,21700002,10/17/2017,HOU @ GSW,1.0,240,47,...,10,33,43,28,9,5,13,16,122,1
47222,22017,1610612763,MEM,Memphis Grizzlies,21700008,10/18/2017,MEM vs. NOP,1.0,240,39,...,15,30,45,19,9,8,12,29,103,12

In [191]:
ratings_2018 = '2018_team_ratings.csv'

In [192]:
ratings_2018 = pd.read_csv(ratings_2018)
ratings_2018.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unadjusted,Unadjusted.1,Unadjusted.2,Unadjusted.3,Adjusted,Adjusted.1,Adjusted.2,Adjusted.3
0,Rk,Team,Conf,Div,W,L,W/L%,MOV,ORtg,DRtg,NRtg,MOV/A,ORtg/A,DRtg/A,NRtg/A
1,1,Houston Rockets,W,SW,65,17,0.793,8.48,115.48,106.84,8.64,8.21,115.45,107.08,8.37
2,2,Toronto Raptors,E,A,59,23,0.72,7.78,114.6,106.56,8.03,7.3,114.5,106.96,7.54
3,3,Golden State Warriors,W,P,58,24,0.707,5.98,114.31,108.43,5.88,5.79,114.33,108.62,5.7
4,4,Utah Jazz,W,NW,48,34,0.585,4.3,109.07,104.56,4.51,4.47,108.92,104.24,4.68

In [193]:
ratings_2018 = ratings_2018.rename(columns=ratings_2018.iloc[0]).drop(ratings_2018.index[0])

In [168]:
merged_df = pd.merge(df_2017, ratings_2018, left_on='TEAM_NAME', right_on='Team')

In [194]:
y = merged_df['WL'].dropna().values.reshape(-1,1)
x = merged_df[['ORtg', 'NRtg']].astype(float)

In [195]:
from sklearn.linear_model import LinearRegression, LogisticRegression
model = LogisticRegression()
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y)

model.fit(X_train,y_train)

C:\Users\jorda\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\jorda\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [196]:
model.score(X_test, y_test)

0.6352941176470588

In [125]:
predicted = model.predict(X)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.